language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node --version
  - npm --version
  - "[[ `node --version` > 'v4.'* ]] && npm run lint || echo \"Skipping lint for Node $(node --version)\""
